### ISSUE TITLE
Estoy recibiendo un error generico todo el tiempo.

### ISSUE THREAD

**Issue by focusrite1** [LucioMSP/ChatGPT-AlexaSkill#1]
![image](https://user-images.githubusercontent.com/65078993/221423103-a7398d4f-e60b-4e1d-907d-70df6c6e7b03.png)

**Comment by LucioD3v** [comment]
¿Si agregaste tu Key?, ¿Cuáles son os Utterances que le añadiste?, Intenta agregando "Pregunta {question} "

**Comment by focusrite1** [comment]
Hola, si agrege mi key  junto a todas las preguntas. Tienes discord / telegram ? Te doy mas detalles alli. https://t.me/p3115 , Pressed#2411 

Tengo experiencia en programacion, por lo que supongo es un error de lenguaje ya que tu lo pusiste en ES-MX y yo en ES-ES ya que soy de Spain. Probe a comprobar las actualizaciones y cambiar varias veces la API key y recibo el mismo error. Espero respuesta

**Comment by focusrite1** [comment]
![image](https://user-images.githubusercontent.com/65078993/221615050-e99a73b8-ddc7-49f3-a73f-0cfc4d54d7e8.png)
![image](https://user-images.githubusercontent.com/65078993/221614941-5b3b929f-0940-4cb3-a614-739fe5882892.png)

**Comment by LucioD3v** [comment]
No tiene nada que ver el idioma pero ya intentaste creando la Skill en es-mx? De igual manera, intentaste invocando bien el Intent con el Utterance: Pregunta "lo que sea!... ? Si entra bien a tu Skill, revisa que te devuelve el JSON

**Comment by focusrite1** [comment]
_"ya intentaste creando la Skill en es-mx?"_  A eso es lo que me refiero en el idioma, pero si estoy equivocado acabo de probar a hacerlo y recibo el mismo error. 

Voy a probar a volver a subir tus archivos haber si realmente es ese el fallo ya que he tocado alguna tonteria y no me he percatado, o si ya es otra cosa. Te voy informando de todas formas aqui esta el JSON. 

![image](https://user-images.githubusercontent.com/65078993/221621314-4372114d-881e-43fb-824a-71743a046618.png)


![image](https://user-images.githubusercontent.com/65078993/221621866-cc4c90c7-fe5a-4704-b0e6-49d253d6b66d.png)
![image](https://user-images.githubusercontent.com/65078993/221621949-b9d26462-2400-441f-b803-39d25c84206f.png)

**Comment by LucioD3v** [comment]
Si quieres compárteme tu código y hago la prueba y te cuento , pero en si no debería de haber ningún problema.

**Comment by focusrite1** [comment]
He vuelto a poner todo tu codigo y recibo exactamente el mismo error. 
![image](https://user-images.githubusercontent.com/65078993/221624571-d331c344-ece8-466a-be5c-c082063549be.png)
 
[amzn1.ask.skill.8670d9ea-2ba3-4c6a-9501-00c3d69a71ce.zip](https://github.com/LucioMSP/ChatGPT-AlexaSkill/files/10841942/amzn1.ask.skill.8670d9ea-2ba3-4c6a-9501-00c3d69a71ce.zip)

Te subo mi codigo.

**Comment by focusrite1** [comment]
Hola, llevo toda la tarde intentando cosas y lo mismo, has conseguido algo?

**Comment by LucioD3v** [comment]
Estas haciendo algo mal. justo acabo de hacer una en el idioma Spanisl (Spain) y funciona perfectamente:

![image](https://user-images.githubusercontent.com/6353852/221682978-d53aeb5d-4b16-4acd-9cc1-cacc9692c0bf.png)

**Comment by focusrite1** [comment]
Has usado tu API key o la mia que era la que venia en el codigo??

**Comment by focusrite1** [comment]
Volvi a hacer todo lo que indicas en el directo mirandolo minuto a minuto, incluso use los mismos parametros que tu y recibo lo mismo, de verdad que no entiendo que pueda ser. Lo unico que se me ocurre es que sea la API. Si puedes dejarme por aqui exactamente el codigo que hiciste + los uterances y tal? Gracias.
![image](https://user-images.githubusercontent.com/65078993/221845055-331e0d92-0d33-42a0-9c20-1cedc2801c9e.png)

**Comment by LucioD3v** [comment]
¿Cómo voy a usar tu API Key? ¿Me la has pasado? He usado la mía claro esta, y el código es el mismo, no se de verdad cual sea tu problema, si quieres mándame un meet de google y lo vemos.

**Comment by focusrite1** [comment]
Hola, si estaria bien hablar por google si te apetece respondeme y lo vemos ahi en un segundo.

**Comment by focusrite1** [comment]
Hola, aqui tienes en enlaze de google meet. https://meet.google.com/xif-siwo-nxc

**Comment by LucioD3v** [comment]
Listo! - Sesión atendida.

**Comment by focusrite1** [comment]
Gracias! Finalmente fue un error de la API no del codigo. Una atencion muy buena
